---
# tasks file for wireguard
- name: Update all packages to the latest version
  apt:
    upgrade: dist
- name: apt-get update as a separate step
  apt:
    update_cache: yes
- name: install dependencies
  package:
    name:
      - python-apt
      - python3-apt
      - software-properties-common
      - ufw
      - iproute2
      - net-tools
      - openssh-server
    state: present
- name: Add wireguard repository from PPA and install its signing key.
  apt_repository:
    repo: ppa:wireguard/wireguard
    update_cache: yes
    validate_certs: yes
- name: apt-get update wireguard
  apt:
   update_cache: yes
- name: install wireguard components
  package:
    name:
      - wireguard-dkms
      - wireguard-tools
      - "linux-headers-{{ ansible_kernel }}"
- name: generate server private and public key
  shell: |
    set -o pipefail
    umask 077
    wg genkey | tee server_private_key | wg pubkey > server_public_key
  args:
    executable: /bin/bash
  changed_when: false
- name: generate server private and public key
  shell: |
    set -o pipefail
    umask 077
    wg genkey | tee client_private_key | wg pubkey > client_public_key
  args:
    executable: /bin/bash
  changed_when: false
- name: set the ipv4 forward
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
- name: Get the PrivateKey
  shell: "cat server_private_key"
  register: PrivateKey
# - set_fact: PrivateKey="{{ PrivateKey.stdout }}"
# - debug: var=PrivateKey
- name: Get the client PublicKey
  shell: "cat client_public_key"
  register: CPublicKey
# - set_fact: PublicKey="{{ PublicKey.stdout }}"
# - debug: var=PublicKey
- name: Create a wg0 server config
  template:
    src: wg0_server.j2
    dest: /etc/wireguard/wg0.conf
- name: Change file ownership, group and permissions
  file:
    path: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '600'
- name: Activate wg0
  command: wg-quick up wg0
- name: Make sure wg service is running
  command: systemctl enable wg-quick@wg0.service