---
# tasks file for sambaS3
- name: install the latest version of samba
  package:
    name:
      - python-apt
      - samba
      - ufw
      - openssh-server
      - restic
    state: present
- name: Ensure group "{{ samba_group }}" exists
  group:
    name: "{{ samba_group }}"
    state: present
- name: Add the user "{{ samba_user }}" with a specific uid and a primary group of "{{ samba_group }}"
  user:
    name: "{{ samba_user }}"
    comment: samba user
    group: "{{ samba_group }}"
- name: Make sure samba is running
  systemd:
    state: started
    enabled: yes
    name: smbd
- name: Make sure ssh is running
  systemd:
    state: started
    enabled: yes
    name: sshd
- name: add a samba password to the user test
  shell: |
    set -o pipefail
    (echo "{{ samba_password }}"; echo "{{ samba_password }}") | smbpasswd -a "{{ samba_user }}"
  args:
    executable: /bin/bash
  changed_when: false
- name: ufw allow smb
  ufw:
    rule: allow
    name: samba
- name: ufw allow ssh
  ufw:
    rule: allow
    port: '22'
    proto: tcp
- name: Recursively change ownership of "{{ STORAGE }}"
  file:
    path: "{{ STORAGE }}"
    state: directory
    recurse: yes
    owner: '{{ samba_user }}'
    group: '{{ samba_group }}'
- name: create a samba share
  template:
    src: smb.j2
    dest: /etc/samba/smb.conf
- include: s3.yml
