---
# tasks file for sambaS3
- name: install the latest version of s3fs samba restic
  package:
    name:
      - python-apt
      - s3fs
      - samba
      - ufw
      - openssh-server
      - restic
    state: latest

- name: Ensure group "security" exists
  group:
    name: security
    state: present

- name: Add the user 'test' with a specific uid and a primary group of 'security'
  user:
    name: test
    comment: samba user
    group: security

- name: Make sure samba is running
  systemd:
    state: started
    enabled: yes
    name: smbd

- name: Make sure ssh is running
  systemd:
    state: started
    enabled: yes
    name: sshd

- name: add a samba password to the user test
  shell: (echo 'test123'; echo 'test123') | smbpasswd -a test
  args:
    executable: /bin/bash

- name: ufw allow smb
  ufw:
    rule: allow
    name: samba

- name: ufw allow ssh
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: create a samba share
  template:
    src: smb.j2
    dest: /etc/samba/smb.conf


# TODO create variables for all role
# TODO - name: mount the hare on s3
