---
- name: install the latest version of s3fs
  package:
    name:
      - s3fs
    state: present
- name: Create a directory if it does not exist
  file:
    path: "{{ STORAGE }}"
    state: directory
    mode: '770'
- name: add s3 password
  template:
    src: passwd-s3fs.j2
    dest: /etc/passwd-s3fs
    owner: root
    group: root
    mode: 0640
    backup: yes
- name: add s3 password to fuse
  template:
    src: fuse.j2
    dest: /etc/fuse.conf
    mode: 0755
- name: mount the s3 bucket
  shell: |
         s3fs "{{ BUCKET }}" "{{ STORAGE }}" \
         -o passwd_file=/etc/passwd-s3fs \
         -o uid=$(id -u '{{ samba_user }}'),gid=$(id -g '{{ samba_user }}'),allow_other,mp_umask=002 \
         -o url="https://s3-'{{ REGION }}'.amazonaws.com"
  args:
    executable: /usr/bin/s3fs
  changed_when: false
  delegate_to: localhost
- name: Ensure fstab uses "s3fs#"{{ BUCKET }}"
  mount:
    name: "{{ STORAGE }}"
    src: "s3fs#{{ BUCKET }}"
    fstype: fuse
    opts: "_netdev,allow_other"
    state: present
